name: default
channels:
- conda-forge
- handley-lab
- nodefaults
dependencies:
- handley-lab::anesthetic ==2.8.14
- astropy >=5.0,<=6.1.2
- astunparse ==1.6.3
- corner ==2.2.2
- decorator >=4.0.0
- dill >=0.3.1.1
- dynesty ==2.1.4
- emcee >=3.1.6
- getdist ==1.4
- h5py >=3.11.0
- ipykernel *
- ipython >=5.3.0
- jax >=0.4.13
- jaxlib >=0.4.13
- jinja2 >=2.9.6
- jsonpickle >=1.4.1
- matplotlib >=3.7.0
- nautilus-sampler ==1.0.4
- networkx >=1.11
- numba *
- numpy >=1.24.0,<=2.0.1
- numpydoc >=1.0.0
- psutil ==6.1.0
- pylops >=1.10.0,<=2.3.1
- pynufft *
- pyprojroot ==0.2.0
- pyswarms ==1.3.0
- python-xxhash <=3.4.1
- pyyaml >=6.0.1
- scikit-image <=0.24.0
- scikit-learn <=1.5.1
- scipy <=1.14.0
- sqlalchemy ==2.0.32
- threadpoolctl >=3.1.0,<=3.2.0
- timeout-decorator ==0.5.0
- typing_inspect >=0.4.0
- ultranest ==3.6.2
- zeus-mcmc ==2.5.4
- pip
- pip:
  - colossus==1.3.1
  - gprof2dot==2021.2.21
  - pyvis==0.3.2
  - -e packages/PyAutoConf
  - -e packages/PyAutoFit
  - -e packages/PyAutoArray
  - -e packages/PyAutoGalaxy
  - -e packages/PyAutoLens
  - -e packages/autojax
