version: "3"

tasks:
  init:
    desc: "Pull all git submodules"
    cmds:
      - git submodule update --init --recursive
  update:
    desc: "Update all git submodules"
    cmds:
      - |
        git submodule foreach '
          # First checkout the appropriate branch
          if [[ $name == "packages/autogalaxy_workspace_test" ]]; then
            git checkout master;
          else
            git checkout main;
          fi;
          git pull
        '
  status:
    desc: "Show the status of all git submodules"
    cmds:
      - git submodule foreach 'git remote -v; git status'
  branch:
    desc: "Show branches each submodule is on"
    cmds:
      - git submodule foreach 'git rev-parse --abbrev-ref HEAD'

  export:
    desc: "Export a conda environment file."
    cmds:
      - pixi project export conda-environment environment.yml
