version: "3"

tasks:
  init:
    desc: "Pull all git submodules"
    cmds:
      - git submodule update --init --recursive
  export:
    desc: "Export a conda environment file."
    cmds:
      - pixi project export conda-environment environment.yml
